### ------------------admin api --------------------
### add new project\
POST http://localhost:4000/admin/add-project
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc2OTk4OSwiZXhwIjoxNjc4Nzc1OTg5fQ.rO1eVwqKqfADf8ii5eP3uxnUAtZVl5mkQfxaWluzG2s
Content-Type: application/json

{
    "project_name":"e commerce",
    "client":"wal",
    "client_account_manager":2,
    "status":"in progress",
    "project_start_date":"2022-12-12",
    "project_fitness_indicator":"green",
    "domain":"webdev",
    "type_of_project":"development",
    "gdo_head":3,
    "project_manager":6
}

### get all projects 
GET http://localhost:4000/admin/projects
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc2OTk4OSwiZXhwIjoxNjc4Nzc1OTg5fQ.rO1eVwqKqfADf8ii5eP3uxnUAtZVl5mkQfxaWluzG2s 

### get specific project details
GET http://localhost:4000/admin/project/1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc2OTk4OSwiZXhwIjoxNjc4Nzc1OTg5fQ.rO1eVwqKqfADf8ii5eP3uxnUAtZVl5mkQfxaWluzG2s 

### get resourcing request by admin on particular project
GET http://localhost:4000/admin/project/2/resource-requests
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc2OTk4OSwiZXhwIjoxNjc4Nzc1OTg5fQ.rO1eVwqKqfADf8ii5eP3uxnUAtZVl5mkQfxaWluzG2s 

### update existing project
PUT http://localhost:4000/admin/edit/project/3
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc2OTk4OSwiZXhwIjoxNjc4Nzc1OTg5fQ.rO1eVwqKqfADf8ii5eP3uxnUAtZVl5mkQfxaWluzG2s 
Content-Type: application/json

{
    "status":"completed"
}
### delete existing project
DELETE http://localhost:4000/admin/edit/project/2
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc2OTk4OSwiZXhwIjoxNjc4Nzc1OTg5fQ.rO1eVwqKqfADf8ii5eP3uxnUAtZVl5mkQfxaWluzG2s 
