####------------------------------------------------------- employee api -------------------------------------------------------------------
# employee registration
POST  http://localhost:4000/employee-registration 
Content-Type: application/json

{
    "employee_name":"gdotest",
    "age":36,
    "gender":"male",
    "email":"gdotest.dummy@westagilelabs.com",
    "password":"gdotest"
}

### employee login
POST http://localhost:4000/employee-login 
Content-Type: application/json

{
    "email":"shamir@westagilelabs.com",
    "password":"shamir123"
}

### forgot password
POST http://localhost:4000/forgot-password
Content-Type: application/json

{
    "email":"shamir@westagilelabs.com"
}
### reset password
PUT  http://localhost:4000/reset-password/shamir@westagilelabs.com
Content-Type: application/json

{
    "otp":723351,
    "password":"shamir123"
}

### -------------------------------------------------------super-admin api----------------------------------------------------------------------
###assign role
PUT  http://localhost:4000/super-admin/assign-role
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hdmVlbkB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImVtcGxveWVlX2lkIjoxLCJpYXQiOjE2Nzg3OTYxNTgsImV4cCI6MTY3OTQwMDk1OH0.1LyqkZzDO-PMWkeMBJeF2BKnfULnv1H6omEPeMRUg1I
Content-Type: application/json

{
    "email":"gdotest.dummy@westagilelabs.com",
    "role":"gdo"
}

### get all employees
GET http://localhost:4000/super-admin/employees
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hdmVlbkB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImVtcGxveWVlX2lkIjoxLCJpYXQiOjE2Nzk5OTg1NDQsImV4cCI6MTY4MDYwMzM0NH0.RZbmY6C3-FZcB0P_v-iQqT_TYEkTbv44ZRQswXT3RF8


### ------------------------------------------------------admin api ----------------------------------------------------------------------------
### add new project\
POST http://localhost:4000/admin/add-project
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY4MDA3MzEwMywiZXhwIjoxNjgwNjc3OTAzfQ.4OWFYOtXj7bHBRN_KctvU2HV2WkiIesRIylIVhJhcDg
Content-Type: application/json

{
    "project_name":"test",
    "client":"wal",
    "client_account_manager":2,
    "status":"in progress",
    "project_start_date":"2022-12-12",
    "project_fitness_indicator":"green",
    "domain":"webdev",
    "type_of_project":"development",
    "gdo_head":7,
    "project_manager":6
}

### get all projects 
GET http://localhost:4000/admin/projects
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3OTk5NDk5NCwiZXhwIjoxNjgwNTk5Nzk0fQ.4VI3CepZPkIAGMjD9k9G_OG_9hAbI2u7DL_OyeE_DKc

### get specific project details
GET http://localhost:4000/admin/project/4
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc5NjE5NCwiZXhwIjoxNjc5NDAwOTk0fQ.BTHaYRc3kvnsD7qPdIEmlzTQLHs3DI4-e95EWyDamac

### get resourcing request by admin on particular project
GET http://localhost:4000/admin/project/1/resource-requests
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY4MDA3OTQwNCwiZXhwIjoxNjgwNjg0MjA0fQ.i_TLUTw1ZazKHlON6GqA8HTvu7DUQx7Fpu61wWkNwmw

### update existing project
PUT http://localhost:4000/admin/edit/project/3
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc5NjE5NCwiZXhwIjoxNjc5NDAwOTk0fQ.BTHaYRc3kvnsD7qPdIEmlzTQLHs3DI4-e95EWyDamac
Content-Type: application/json

{
    "status":"completed"
}
### delete existing project
DELETE http://localhost:4000/admin/edit/project/4
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhc2hpQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImFkbWluIiwiZW1wbG95ZWVfaWQiOjIsImlhdCI6MTY3ODc5NjE5NCwiZXhwIjoxNjc5NDAwOTk0fQ.BTHaYRc3kvnsD7qPdIEmlzTQLHs3DI4-e95EWyDamac


### -----------------------------------------------------------gdo api ------------------------------------------------------------------------
### get all projects under gdo
GET http://localhost:4000/gdo/projects
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdkb3Rlc3QuZHVtbXlAd2VzdGFnaWxlbGFicy5jb20iLCJyb2xlIjoiZ2RvIiwiZW1wbG95ZWVfaWQiOjcsImlhdCI6MTY3ODc5Nzg3MSwiZXhwIjoxNjc5NDAyNjcxfQ.o3t07GxAtE4NZGkQf8G9wjXEcNAdY4NhRJv7_CBLA9s

### get all employees
GET http://localhost:4000/gdo/employees
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVuQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImdkbyIsImVtcGxveWVlX2lkIjozLCJpYXQiOjE2Nzg3OTYyNjAsImV4cCI6MTY3OTQwMTA2MH0.PazB70xYq7eYWYXIjTGkLlbcpVmEm28zGpXU0NTznyw
### assign team
POST http://localhost:4000/gdo/assign-team 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVuQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImdkbyIsImVtcGxveWVlX2lkIjozLCJpYXQiOjE2Nzg3OTYyNjAsImV4cCI6MTY3OTQwMTA2MH0.PazB70xYq7eYWYXIjTGkLlbcpVmEm28zGpXU0NTznyw
Content-Type: application/json

{
    
    "team_composition":[
        {
            "project_id":4,
            "role_in_project":"dev",
            "start_date":"2023-02-23",
            "status":"active",
            "billing_status":"billed",
            "exposed_to_customer":true,
            "allocation_type":"temporary"
        },
        {
            "project_id":4,
            "role_in_project":"frontend dev",
            "start_date":"2023-03-10",
            "status":"active",
            "billing_status":"buffered",
            "exposed_to_customer":false,
            "allocation_type":"temporary"
        }
    ]
    
}

### get specific project details
GET http://localhost:4000/gdo/project/5
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW1pckB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NSwiaWF0IjoxNjgwMTU4MDYyLCJleHAiOjE2ODA3NjI4NjJ9.sUHMG1wqq1s1AugN2l9apn634Jin_Drvp9dNI-qT4fA

### raise resourcing request
POST http://localhost:4000/gdo/project/1/resource-request
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVuQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImdkbyIsImVtcGxveWVlX2lkIjozLCJpYXQiOjE2Nzg3OTYyNjAsImV4cCI6MTY3OTQwMTA2MH0.PazB70xYq7eYWYXIjTGkLlbcpVmEm28zGpXU0NTznyw
Content-Type: application/json

{
    "resource_desc":"need developers"
}

### update status of teammate in team by gdo

### ------------------------------------------------------------- manager api --------------------------------------------------------
### get projects under manager
GET http://localhost:4000/manager/projects 
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW1pckB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NSwiaWF0IjoxNjgwMTQ5MTUwLCJleHAiOjE2ODA3NTM5NTB9.jCyV5qV9UUYGL-ghiq5CrMs5aHY8y9-CgamflvlcxK4

### get specific details of project
GET http://localhost:4000/manager/project/5
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW1pckB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NSwiaWF0IjoxNjgwMTU4MDYyLCJleHAiOjE2ODA3NjI4NjJ9.sUHMG1wqq1s1AugN2l9apn634Jin_Drvp9dNI-qT4fA
### raise concern
POST http://localhost:4000/manager/project-concern
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYWl0YW55YUB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NiwiaWF0IjoxNjc4Nzk2MzM2LCJleHAiOjE2Nzk0MDExMzZ9.yL0iy_ycZcA2bDE2OP1PRBcDJoNj1dsNiH0TEPlywuA
Content-Type: application/json

{
    "project_concerns":
    {
        "project_id":1,
        "concern_desc":"lack of developers",
        "concern_raised_by":"manager",
        "severity_of_concern":"extreme",
        "concern_raised_by_client":false,
        "status_of_concern":"pending"
    }
}

### modify existing project concern
PUT http://localhost:4000/manager/modify-project-concern/2
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYWl0YW55YUB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NiwiaWF0IjoxNjc4Nzk2MzM2LCJleHAiOjE2Nzk0MDExMzZ9.yL0iy_ycZcA2bDE2OP1PRBcDJoNj1dsNiH0TEPlywuA
Content-Type: application/json

{
    "project_id":1,
    "status_of_concern":"fullfilled"   
}

### project update
POST http://localhost:4000/manager/project-update
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYWl0YW55YUB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NiwiaWF0IjoxNjc4Nzk2MzM2LCJleHAiOjE2Nzk0MDExMzZ9.yL0iy_ycZcA2bDE2OP1PRBcDJoNj1dsNiH0TEPlywuA
Content-Type: application/json

{
    "project_updates":{
    "project_id":4,
    "project_status":"backend development completed",
    "date":"2023-01-20",
    "schedule_status":"green",
    "resourcing_status":"green",
    "quality_status":"green",
    "waiting_for_client_ip":false
    }
}

### modify existing project updates
PUT http://localhost:4000/manager/modify-project-update/1
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYWl0YW55YUB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJwcm9qZWN0LW1hbmFnZXIiLCJlbXBsb3llZV9pZCI6NiwiaWF0IjoxNjc4Nzk2MzM2LCJleHAiOjE2Nzk0MDExMzZ9.yL0iy_ycZcA2bDE2OP1PRBcDJoNj1dsNiH0TEPlywuA
Content-Type: application/json

{
    "schedule_status":"red"   
}
