####             ------------ employee api ----------------
# employee registration
POST  http://localhost:4000/employee-registration 
Content-Type: application/json

{
    "employee_name":"chaitanya",
    "age":21,
    "gender":"male",
    "email":"chaitanya@westagilelabs.com",
    "password":"chaitanya"
}

### employee login
POST http://localhost:4000/employee-login 
Content-Type: application/json

{
    "email":"sashi@westagilelabs.com",
    "password":"sashi"
}

### forgot password

### reset password


