
### -----------------gdo api ---------------------------
### get all projects under gdo
GET http://localhost:4000/projects
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVuQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImdkbyIsImVtcGxveWVlX2lkIjozLCJpYXQiOjE2Nzg3MDI3NTQsImV4cCI6MTY3ODcwODc1NH0.sLr1qsTZ5kqPHLGyNOuEnHK0hMfpea6O_nlsaHGwD3c
### assign team
POST http://localhost:4000/assign-team 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhcnVuQHdlc3RhZ2lsZWxhYnMuY29tIiwicm9sZSI6ImdkbyIsImlhdCI6MTY3ODcwMjAwOCwiZXhwIjoxNjc4NzA4MDA4fQ.CIH_RdAuca48WYYFGl-A2PC7AEHF3VpR1hKZaWJgfN8
Content-Type: application/json

{
    
    "team_composition":[
        {
            "project_id":1,
            "role_in_project":"dev",
            "start_date":"2023-02-23",
            "status":"active",
            "billing_status":"billed",
            "exposed_to_customer":true,
            "allocation_type":"temporary"
        },
        {
            "project_id":1,
            "role_in_project":"frontend dev",
            "start_date":"2023-03-10",
            "status":"active",
            "billing_status":"buffered",
            "exposed_to_customer":false,
            "allocation_type":"temporary"
        }
    ]
    
}

### get specific project details

### update existing employee details

### raise resourcing request
