### -----------------super-admin api----------------------
###assign role
PUT  http://localhost:4000/super-admin/assign-role
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hdmVlbkB3ZXN0YWdpbGVsYWJzLmNvbSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImlhdCI6MTY3ODcwMTU2MCwiZXhwIjoxNjc4NzA3NTYwfQ.qhL5oLTqnvL_lt77DBheILoBTd98v8i2PnqV0pwECAc
Content-Type: application/json

{
    "email":"chaitanya@westagilelabs.com",
    "role":"project-manager"
}

### get all data of gdos
GET http://localhost:4000/super-admin/dashboard